//! 代码生成器（核心入口）
//!
//! 将 AST 转换为 Rust 源码字符串（`impl Render for <View>`）。
//! 详见文档 §10.6 代码生成。
//!
//! 生成代码通过 `include!` 注入用户模块，因此：
//! - 全部使用完全限定路径（`gpui::*`、`rml::runtime::*`），避免与用户 import 冲突
//! - 事件回调统一通过 `rml::runtime::event_flow::convert::from_gpui_*` 转换 GPUI 事件 → RML 事件
//! - GPUI 事件监听器（on_click 等）要求元素为 `Stateful<Div>`，需先调用 `.id(...)` 赋予 ID
//!
//! ## 模块职责
//!
//! - `mod.rs`（本文件）：入口 `codegen()` 函数，按根标签分派到 window/observable/render
//! - `node.rs`：节点代码生成（gen_node + gen_element）
//! - `attribute.rs`：属性代码生成（静态/CSS/内联/绑定）
//! - `text.rs`：文本与表达式代码生成（混合文本/插值/i18n）
//! - `model.rs`：Model 字段收集
//! - `render.rs`：`impl Render` 生成
//! - `window.rs`：窗口/对话框 impl 生成（`impl IWindow` / `open`+`close`）
//! - `shell.rs`：窗口外壳包裹（ModernWindowShell / TabWindowShell）
//! - `binding.rs`：双向绑定与字段校验代码生成
//! - `observable.rs`：Observable 版本管理 + 计算属性缓存 + InputState 同步
//! - `event.rs`：事件绑定代码生成（onclick → .on_click 等）
//! - `component.rs`：gpui-component 扩展组件生成（Button/Input 等）
//! - `expr.rs`：表达式解析器（{count + 1} → AST → Rust 代码）

mod attribute;
mod binding;
mod lifecycle;
mod model;
mod node;
mod observable;
mod render;
mod shell;
mod text;
mod window;

use crate::compiler::{CodegenCtx, CodegenError};
use crate::tags;

pub use model::{collect_model_converters, collect_model_fields, collect_model_input_handlers};
pub use node::{gen_node, GenResult};
pub(crate) use text::{gen_expr_code, try_gen_i18n_call};

use render::{gen_render_impl_from_children, ShellWrap};

/// 生成 `impl Render for <ViewStruct>` 代码块（可能附带 `impl IWindow`）
///
/// RML 根节点必须是 `<window>`、`<modern-window>`、`<tab-window>`、`<dialog>` 或 `<component>`：
/// - `<window>`/`<modern-window>`/`<tab-window>`：生成 `impl IWindow` + `impl Render`
/// - `<dialog>`：生成 `open(window, cx)` / `close(cx)` 方法 + `impl Render`
/// - `<component>`：仅生成 `impl Render`
pub fn codegen(root: &crate::parser::ast::Node, ctx: &CodegenCtx) -> Result<String, CodegenError> {
    use crate::parser::ast::Node;

    let elem = match root {
        Node::Element(e) if tags::is_root_tag(&e.tag) => e,
        _ => {
            return Err(CodegenError {
                message: format!(
                    "root element must be <window>, <modern-window>, <tab-window>, <dialog>, or <component>; got <{}>",
                    root
                ),
            });
        }
    };

    let root_tag = tags::root_tag_lookup(&elem.tag)
        .ok_or_else(|| CodegenError { message: format!("invalid root tag: <{}>", elem.tag) })?;

    let mut out = String::new();
    out.push_str("// Auto-generated by RML compiler. DO NOT EDIT.\n");
    out.push_str("#[allow(unused_imports, unused_variables, non_snake_case, dead_code)]\n\n");

    let shell_wrap = match root_tag {
        tags::RootTag::ModernWindow => ShellWrap::Modern,
        tags::RootTag::TabWindow => ShellWrap::Tab,
        _ => ShellWrap::None,
    };

    let chrome_transparent = matches!(
        root_tag,
        tags::RootTag::ModernWindow | tags::RootTag::TabWindow
    );

    // 1. 窗口/对话框类型：生成对应 impl
    match root_tag {
        tags::RootTag::Window => {
            out.push_str(&window::gen_window_impl(elem, ctx, false)?);
            out.push('\n');
        }
        tags::RootTag::ModernWindow | tags::RootTag::TabWindow => {
            out.push_str(&window::gen_window_impl(elem, ctx, chrome_transparent)?);
            out.push('\n');
        }
        tags::RootTag::DialogWindow => {
            out.push_str(&window::gen_dialog_impl(elem, ctx)?);
            out.push('\n');
        }
        tags::RootTag::Component => {}
    }

    // 2. 生成 impl Render
    out.push_str(&gen_render_impl_from_children(elem, ctx, shell_wrap)?);

    // 3. 版本管理方法 + 计算属性包装方法
    out.push_str(&observable::gen_observable_impl(ctx));
    out.push('\n');
    out.push_str(&observable::gen_computed_wrappers(ctx));
    out.push('\n');

    // 4. InputState 惰性初始化方法
    out.push_str(&observable::gen_input_state_impl(ctx));

    // 5. 生命周期钩子自动联动（#[on_loaded]/#[on_unloaded] → impl ILifecycle）
    out.push_str(&lifecycle::gen_lifecycle_impl(ctx));

    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::compiler::CodegenCtx;
    use crate::parser::ast::Node;

    /// 构造最小可用的 CodegenCtx：仅设置 view_struct_name，其余字段保持 Default。
    fn minimal_ctx() -> CodegenCtx {
        CodegenCtx {
            view_struct_name: "TestView".to_string(),
            ..Default::default()
        }
    }

    // ─── 错误路径：非 Element 根节点 ───

    #[test]
    fn codegen_text_root_returns_error() {
        let root = Node::Text("hello".to_string());
        let result = codegen(&root, &minimal_ctx());
        assert!(result.is_err());
        let err = result.unwrap_err();
        assert!(
            err.message.contains("root element must be"),
            "expected root element error, got: {}",
            err.message
        );
    }

    #[test]
    fn codegen_interpolation_root_returns_error() {
        let root = Node::Interpolation("count".to_string());
        let result = codegen(&root, &minimal_ctx());
        assert!(result.is_err());
    }

    #[test]
    fn codegen_mixed_text_root_returns_error() {
        let root = Node::MixedText(vec![]);
        let result = codegen(&root, &minimal_ctx());
        assert!(result.is_err());
    }

    // ─── 错误路径：Element 但非根标签 ───

    #[test]
    fn codegen_non_root_tag_returns_error() {
        // <div> 不是根标签（window/modern-window/tab-window/dialog/component）
        let root = crate::parser::parse("<div></div>").unwrap();
        let result = codegen(&root, &minimal_ctx());
        assert!(result.is_err());
        let err = result.unwrap_err();
        assert!(
            err.message.contains("root element must be"),
            "expected root element error, got: {}",
            err.message
        );
    }

    #[test]
    fn codegen_button_root_returns_error() {
        let root = crate::parser::parse("<button></button>").unwrap();
        assert!(codegen(&root, &minimal_ctx()).is_err());
    }

    // ─── 成功路径：各根标签可生成代码 ───

    #[test]
    fn codegen_component_root_succeeds() {
        let root = crate::parser::parse("<component></component>").unwrap();
        let result = codegen(&root, &minimal_ctx());
        assert!(result.is_ok(), "codegen failed: {:?}", result.err());
        let code = result.unwrap();
        // 确认生成代码包含自动生成注释和 impl Render
        assert!(
            code.contains("// Auto-generated by RML compiler. DO NOT EDIT."),
            "expected auto-generated header"
        );
        assert!(
            code.contains("impl gpui::Render for TestView"),
            "expected impl Render for TestView, got snippet: {}",
            code.chars().take(300).collect::<String>()
        );
    }

    #[test]
    fn codegen_window_root_succeeds() {
        let root = crate::parser::parse("<window></window>").unwrap();
        let result = codegen(&root, &minimal_ctx());
        assert!(result.is_ok(), "codegen failed: {:?}", result.err());
        let code = result.unwrap();
        assert!(code.contains("impl gpui::Render for TestView"));
    }

    #[test]
    fn codegen_dialog_root_succeeds() {
        let root = crate::parser::parse("<dialog></dialog>").unwrap();
        let result = codegen(&root, &minimal_ctx());
        assert!(result.is_ok(), "codegen failed: {:?}", result.err());
        let code = result.unwrap();
        assert!(code.contains("impl gpui::Render for TestView"));
    }

    #[test]
    fn codegen_modern_window_root_succeeds() {
        let root = crate::parser::parse("<modern-window></modern-window>").unwrap();
        let result = codegen(&root, &minimal_ctx());
        assert!(result.is_ok(), "codegen failed: {:?}", result.err());
        let code = result.unwrap();
        assert!(code.contains("impl gpui::Render for TestView"));
    }

    #[test]
    fn codegen_tab_window_root_succeeds() {
        let root = crate::parser::parse("<tab-window></tab-window>").unwrap();
        let result = codegen(&root, &minimal_ctx());
        assert!(result.is_ok(), "codegen failed: {:?}", result.err());
        let code = result.unwrap();
        assert!(code.contains("impl gpui::Render for TestView"));
    }

    // ─── 烟雾测试：生成代码结构完整性 ───

    #[test]
    fn codegen_component_with_child_generates_render_body() {
        // <component><div></div></component> → render 方法体非空
        let root = crate::parser::parse("<component><div></div></component>").unwrap();
        let code = codegen(&root, &minimal_ctx()).unwrap();
        // render 方法签名应出现
        assert!(
            code.contains("fn render(&mut self, _window: &mut gpui::Window, cx: &mut gpui::Context<Self>)"),
            "expected render method signature"
        );
    }

    #[test]
    fn codegen_includes_rml_render_guard() {
        // 所有 codegen 输出应包含 RenderThreadGuard::enter() 调用
        let root = crate::parser::parse("<component></component>").unwrap();
        let code = codegen(&root, &minimal_ctx()).unwrap();
        assert!(
            code.contains("RenderThreadGuard::enter()"),
            "expected RenderThreadGuard::enter() in generated code"
        );
    }

    #[test]
    fn codegen_includes_lifecycle_hook_call() {
        // 所有 codegen 输出应在 render 入口处调用 on_loaded（仅首次）
        let root = crate::parser::parse("<component></component>").unwrap();
        let code = codegen(&root, &minimal_ctx()).unwrap();
        assert!(
            code.contains("ILifecycle::on_loaded"),
            "expected ILifecycle::on_loaded call in render"
        );
    }

    #[test]
    fn codegen_empty_component_uses_div_placeholder() {
        // 空子节点应使用 gpui::div() 占位
        let root = crate::parser::parse("<component></component>").unwrap();
        let code = codegen(&root, &minimal_ctx()).unwrap();
        assert!(
            code.contains("gpui::div()"),
            "expected gpui::div() placeholder for empty body"
        );
    }
}
