//! 代码生成器（核心）
//!
//! 将 AST 转换为 Rust 源码字符串（`impl Render for <View>`）。
//! 详见文档 §10.6 代码生成。
//!
//! 生成代码通过 `include!` 注入用户模块，因此：
//! - 全部使用完全限定路径（`gpui::*`、`rml::runtime::*`），避免与用户 import 冲突
//! - 事件回调统一通过 `rml::runtime::event_flow::convert::from_gpui_*` 转换 GPUI 事件 → RML 事件
//! - GPUI 事件监听器（on_click 等）要求元素为 `Stateful<Div>`，需先调用 `.id(...)` 赋予 ID
//!
//! ## 模块职责
//!
//! - `mod.rs`（本文件）：核心元素生成（div/h1/ul 等 + 指令 + 插值 + 属性）
//! - `window.rs`：窗口/对话框 impl 生成（`impl IWindow` / `open`+`close`）
//! - `shell.rs`：窗口外壳包裹（ModernWindowShell / TabWindowShell）
//! - `binding.rs`：双向绑定与字段校验代码生成
//! - `observable.rs`：Observable 版本管理 + 计算属性缓存 + InputState 同步
//! - `event.rs`：事件绑定代码生成（onclick → .on_click 等）
//! - `component.rs`：gpui-component 扩展组件生成（Button/Input 等）
//! - `expr.rs`：表达式解析器（{count + 1} → AST → Rust 代码）

mod binding;
mod observable;
mod shell;
mod window;

use crate::compiler::expr;
use crate::compiler::{CodegenCtx, CodegenError};
use crate::css;
use crate::parser::ast::{Attribute, Directive, Element, Node, TextSegment};
use crate::tags;
use crate::compiler::component as comp;
use crate::compiler::event;

/// 收集 RML 中所有 `model={field}` 绑定的字段名
pub fn collect_model_fields(root: &Node) -> Vec<String> {
    let mut fields = Vec::new();
    if let Node::Element(elem) = root {
        collect_model_fields_recursive(elem, &mut fields);
    }
    fields.sort();
    fields.dedup();
    fields
}

fn collect_model_fields_recursive(elem: &Element, fields: &mut Vec<String>) {
    for directive in &elem.directives {
        if let Directive::Model(field) = directive {
            fields.push(field.clone());
        }
    }
    for child in &elem.children {
        if let Node::Element(child_elem) = child {
            collect_model_fields_recursive(child_elem, fields);
        }
    }
}

/// 生成 `impl Render for <ViewStruct>` 代码块（可能附带 `impl IWindow`）
///
/// RML 根节点必须是 `<window>`、`<modern_window>`、`<tab_window>`、`<dialog>` 或 `<component>`：
/// - `<window>`/`<modern_window>`/`<tab_window>`：生成 `impl IWindow` + `impl Render`
/// - `<dialog>`：生成 `open(window, cx)` / `close(cx)` 方法 + `impl Render`
/// - `<component>`：仅生成 `impl Render`
pub fn codegen(root: &Node, ctx: &CodegenCtx) -> Result<String, CodegenError> {
    let elem = match root {
        Node::Element(e) if tags::is_root_tag(&e.tag) => e,
        _ => {
            return Err(CodegenError {
                message: format!(
                    "root element must be <window>, <modern_window>, <tab_window>, <dialog>, or <component>; got <{}>",
                    root
                ),
            });
        }
    };

    let root_tag = tags::root_tag_lookup(&elem.tag)
        .ok_or_else(|| CodegenError { message: format!("invalid root tag: <{}>", elem.tag) })?;

    let mut out = String::new();
    out.push_str("// Auto-generated by RML compiler. DO NOT EDIT.\n");
    out.push_str("#[allow(unused_imports, unused_variables, non_snake_case, dead_code)]\n\n");

    let shell_wrap = match root_tag {
        tags::RootTag::ModernWindow => ShellWrap::Modern,
        tags::RootTag::TabWindow => ShellWrap::Tab,
        _ => ShellWrap::None,
    };

    let chrome_transparent = matches!(
        root_tag,
        tags::RootTag::ModernWindow | tags::RootTag::TabWindow
    );

    // 1. 窗口/对话框类型：生成对应 impl
    match root_tag {
        tags::RootTag::Window => {
            out.push_str(&window::gen_window_impl(elem, ctx, false)?);
            out.push('\n');
        }
        tags::RootTag::ModernWindow | tags::RootTag::TabWindow => {
            out.push_str(&window::gen_window_impl(elem, ctx, chrome_transparent)?);
            out.push('\n');
        }
        tags::RootTag::DialogWindow => {
            out.push_str(&window::gen_dialog_impl(elem, ctx)?);
            out.push('\n');
        }
        tags::RootTag::Component => {}
    }

    // 2. 生成 impl Render
    out.push_str(&gen_render_impl_from_children(elem, ctx, shell_wrap)?);

    // 3. 版本管理方法 + 计算属性包装方法
    out.push_str(&observable::gen_observable_impl(ctx));
    out.push('\n');
    out.push_str(&observable::gen_computed_wrappers(ctx));
    out.push('\n');

    // 4. InputState 惰性初始化方法
    out.push_str(&observable::gen_input_state_impl(ctx));

    Ok(out)
}

/// 窗口壳包裹类型
enum ShellWrap {
    None,
    Modern,
    Tab,
}

/// 从根节点的子节点生成 `impl Render`
///
/// 单个子节点：直接使用其代码。多个子节点：包裹在 `gpui::div()` 中。
/// 零子节点：使用 `gpui::div()` 作为占位。
fn gen_render_impl_from_children(
    elem: &Element,
    ctx: &CodegenCtx,
    shell: ShellWrap,
) -> Result<String, CodegenError> {
    let view_name = &ctx.view_struct_name;
    let mut out = String::new();

    out.push_str("#[allow(unused_imports, unused_variables, non_snake_case, dead_code)]\n");
    out.push_str(&format!("impl gpui::Render for {} {{\n", view_name));
    out.push_str(
        "    fn render(&mut self, _window: &mut gpui::Window, cx: &mut gpui::Context<Self>) -> impl gpui::IntoElement {\n",
    );
    out.push_str("        if !self.__rml_loaded {\n");
    out.push_str("            self.__rml_loaded = true;\n");
    out.push_str("            rml_core::lifecycle::ILifecycle::on_loaded(self, _window, cx);\n");
    out.push_str("        }\n");
    out.push_str("        use gpui::{ParentElement, InteractiveElement, StatefulInteractiveElement, IntoElement, Styled};\n");
    out.push_str("        use rml_ui::{ButtonVariants, Disableable, Sizable, Selectable, StyledExt};\n");
    out.push_str("        use rml::runtime::event_flow::convert as rml_convert;\n");

    let mut id_counter: usize = 0;
    let empty: Vec<String> = Vec::new();

    let (slot_menu, slot_title, slot_footer, slot_left, slot_right, slot_bottom, body_children) =
        if matches!(shell, ShellWrap::Tab | ShellWrap::Modern) {
            shell::partition_slot_children(&elem.children)
        } else {
            (None, None, None, None, None, None, elem.children.clone())
        };

    let body = if body_children.is_empty() {
        "gpui::div()".to_string()
    } else if body_children.len() == 1 {
        let (code, _) = gen_node(&body_children[0], ctx, 0, &mut id_counter, &empty)?;
        code
    } else {
        let mut code = String::from("gpui::div()");
        for child in &body_children {
            let (child_code, _) = gen_node(child, ctx, 0, &mut id_counter, &empty)?;
            code.push_str(&format!("\n            .child({})", child_code));
        }
        code
    };

    let slot_menu_code = slot_menu
        .as_ref()
        .map(|node| gen_node(node, ctx, 0, &mut id_counter, &empty).map(|(c, _)| c))
        .transpose()?;
    let slot_title_code = slot_title
        .as_ref()
        .map(|node| gen_node(node, ctx, 0, &mut id_counter, &empty).map(|(c, _)| c))
        .transpose()?;
    let slot_footer_code = slot_footer
        .as_ref()
        .map(|node| gen_node(node, ctx, 0, &mut id_counter, &empty).map(|(c, _)| c))
        .transpose()?;
    let slot_left_code = slot_left
        .as_ref()
        .map(|node| gen_node(node, ctx, 0, &mut id_counter, &empty).map(|(c, _)| c))
        .transpose()?;
    let slot_right_code = slot_right
        .as_ref()
        .map(|node| gen_node(node, ctx, 0, &mut id_counter, &empty).map(|(c, _)| c))
        .transpose()?;
    let slot_bottom_code = slot_bottom
        .as_ref()
        .map(|node| gen_node(node, ctx, 0, &mut id_counter, &empty).map(|(c, _)| c))
        .transpose()?;

    let final_body = match shell {
        ShellWrap::Modern => shell::gen_modern_window_wrapper(
            elem,
            ctx,
            &body,
            slot_title_code.as_deref(),
            slot_footer_code.as_deref(),
        )?,
        ShellWrap::Tab => shell::gen_tab_window_wrapper(
            elem,
            ctx,
            &body,
            slot_menu_code.as_deref(),
            slot_title_code.as_deref(),
            slot_footer_code.as_deref(),
            slot_left_code.as_deref(),
            slot_right_code.as_deref(),
            slot_bottom_code.as_deref(),
        )?,
        ShellWrap::None => body,
    };

    // 窗口根节点自动注入 Dialog/Sheet/Notification 渲染层。
    // `<component>` 与 `<dialog>` 不注入（dialog 自身是 layer 内的 child）。
    let with_layers = if matches!(shell, ShellWrap::Modern | ShellWrap::Tab)
        || root_tag_is_window(elem)
    {
        format!(
            "{{\n            \
             let __rml_body = {body};\n            \
             gpui::div()\n                \
             .size_full()\n                \
             .child(__rml_body)\n                \
             .children(rml_ui::Root::render_dialog_layer(_window, cx))\n                \
             .children(rml_ui::Root::render_sheet_layer(_window, cx))\n                \
             .children(rml_ui::Root::render_notification_layer(_window, cx))\n            \
             }}",
            body = final_body
        )
    } else {
        final_body
    };

    out.push_str(&format!("        {}\n", with_layers));
    out.push_str("    }\n");
    out.push_str("}\n");

    Ok(out)
}

/// 判断元素是否为窗口根节点（window/modern_window/tab_window）
fn root_tag_is_window(elem: &Element) -> bool {
    matches!(
        tags::root_tag_lookup(&elem.tag),
        Some(tags::RootTag::Window | tags::RootTag::ModernWindow | tags::RootTag::TabWindow)
    )
}

/// codegen 结果：元素代码 + 是否为迭代器
pub type GenResult = (String, bool);

/// 为单个节点生成构建代码，返回 (代码, 是否迭代器)
pub fn gen_node(
    node: &Node,
    ctx: &CodegenCtx,
    depth: usize,
    id_counter: &mut usize,
    loop_vars: &[String],
) -> Result<GenResult, CodegenError> {
    let lv: Vec<&str> = loop_vars.iter().map(|s| s.as_str()).collect();
    let computed: Vec<&str> = ctx.computed_methods.iter().map(|s| s.as_str()).collect();
    match node {
        Node::Element(elem) => gen_element(elem, ctx, depth, id_counter, loop_vars),
        Node::Text(text) => Ok((format!("{:?}", text), false)),
        Node::Interpolation(expr_str) => {
            Ok((
                format!("format!(\"{{}}\", {})", gen_expr_code(expr_str, &lv, &computed)),
                false,
            ))
        }
        Node::MixedText(segments) => {
            Ok((gen_mixed_text(segments, &lv, &computed), false))
        }
    }
}

fn gen_element(
    elem: &Element,
    ctx: &CodegenCtx,
    depth: usize,
    id_counter: &mut usize,
    loop_vars: &[String],
) -> Result<GenResult, CodegenError> {
    let tag = &elem.tag;

    // 扩展组件（PascalCase 或特殊小写标签 menu/status_bar）：路由到 gpui-component 构造器
    if tags::is_component(tag) || tags::is_special_lowercase_component(tag) {
        let code = comp::gen_component(elem, ctx, depth, id_counter, loop_vars)?;
        return Ok((code, false));
    }

    // model 指令：input/textarea 的双向绑定
    let model_field = elem.directives.iter().find_map(|d| match d {
        Directive::Model(f) => Some(f.clone()),
        _ => None,
    });

    if model_field.is_some() && (tag == "input" || tag == "textarea") {
        let code = binding::gen_model_input(elem, ctx, id_counter, model_field.unwrap())?;
        return Ok((code, false));
    }

    let builtin = tags::lookup(tag).ok_or_else(|| CodegenError {
        message: format!("unknown tag: <{}>", tag),
    })?;

    let each_clause = elem.directives.iter().find_map(|d| match d {
        Directive::Each(c) => Some(c.clone()),
        _ => None,
    });

    let mut child_loop_vars: Vec<String> = loop_vars.to_vec();
    if let Some(clause) = &each_clause {
        child_loop_vars.push(clause.item.clone());
        if let Some(idx) = &clause.index {
            child_loop_vars.push(idx.clone());
        }
    }
    let lv: Vec<&str> = child_loop_vars.iter().map(|s| s.as_str()).collect();

    // 1. 生成元素构造调用
    let mut code = String::from(builtin.codegen_ctor());

    // 2. ref 指令或事件处理器：生成 .id()
    let ref_name: Option<&str> = elem.directives.iter().find_map(|d| match d {
        Directive::Ref(name) => Some(name.as_str()),
        _ => None,
    });

    let has_events = elem
        .attributes
        .iter()
        .any(|attr| matches!(attr, Attribute::Event { .. }));

    if let Some(name) = ref_name {
        code.push_str(&format!(".id({:?})", format!("rml_ref:{}", name)));
    } else if has_events {
        let id_val = *id_counter;
        *id_counter += 1;
        code.push_str(&format!(".id((\"rml_el\", {}usize))", id_val));
    }

    // 2b. 应用 CSS 样式（class/id 属性匹配全局样式表）
    if let Some(sheet) = &ctx.stylesheet {
        let style_code = apply_css_styles(elem, tag, sheet);
        if !style_code.is_empty() {
            code.push_str(&style_code);
        }
    }

    // 3. 应用静态属性与绑定属性
    for attr in &elem.attributes {
        match attr {
            Attribute::Static { name, value } => {
                code.push_str(&apply_static_attr(name, value));
            }
            Attribute::Bind { name, expr } => {
                let computed: Vec<&str> = ctx.computed_methods.iter().map(|s| s.as_str()).collect();
                code.push_str(&apply_bind_attr(name, expr, &lv, &computed));
            }
            Attribute::Event { name, handler } => {
                code.push_str(&event::apply_event(name, handler, ctx));
            }
        }
    }

    // 4. 处理子节点
    for child in &elem.children {
        let (child_code, is_iter) = gen_node(child, ctx, depth + 1, id_counter, &child_loop_vars)?;
        if is_iter {
            code.push_str(&format!("\n            .children({})", child_code));
        } else {
            code.push_str(&format!("\n            .child({})", child_code));
        }
    }

    // 5. 处理 each 指令：将元素包装在迭代器中
    if let Some(clause) = each_clause {
        let iter_code = format!(
            "self.{}.iter().map(|{}| {{\n                {}\n            }})",
            clause.iterable, clause.item, code
        );
        return Ok((iter_code, true));
    }

    // 6. 处理 if/show 指令：条件渲染
    let cond: Option<String> = elem.directives.iter().find_map(|d| match d {
        Directive::If(c) => Some(c.clone()),
        Directive::Show(c) => Some(c.clone()),
        _ => None,
    });

    if let Some(cond) = cond {
        let computed: Vec<&str> = ctx.computed_methods.iter().map(|s| s.as_str()).collect();
        let cond_code = gen_expr_code(&cond, &lv, &computed);
        let cond_code = cond_code
            .strip_prefix('(')
            .and_then(|s| s.strip_suffix(')'))
            .map(|s| s.to_string())
            .unwrap_or(cond_code);
        Ok((
            format!(
                "if {} {{ {}.into_any_element() }} else {{ gpui::Empty.into_any_element() }}",
                cond_code, code
            ),
            false,
        ))
    } else {
        Ok((code, false))
    }
}

fn apply_static_attr(name: &str, value: &str) -> String {
    match name {
        "class" | "id" => String::new(),
        "ref" => String::new(),
        "style" => apply_inline_style(value),
        "src" | "href" => String::new(),
        "type" => String::new(),
        _ => format!(".child({:?})", format!("{}={}", name, value)),
    }
}

/// 从元素的 class/id 属性提取值，匹配 CSS 样式表，返回 GPUI 方法调用代码
fn apply_css_styles(elem: &Element, tag: &str, sheet: &css::StyleSheet) -> String {
    let class_value: String = elem
        .attributes
        .iter()
        .find_map(|attr| match attr {
            Attribute::Static { name, value } if name == "class" => Some(value.clone()),
            _ => None,
        })
        .unwrap_or_default();

    let id_value: Option<&str> = elem
        .attributes
        .iter()
        .find_map(|attr| match attr {
            Attribute::Static { name, value } if name == "id" => Some(value.as_str()),
            _ => None,
        });

    if class_value.is_empty() && id_value.is_none() {
        return String::new();
    }

    css::styles_for_class(sheet, tag, &class_value, id_value)
}

/// 解析 inline style 属性（如 `style="padding: 10px; color: red;"`）
fn apply_inline_style(style_str: &str) -> String {
    let wrapped = format!("* {{ {} }}", style_str);
    match css::parse(&wrapped) {
        Ok(sheet) => {
            if sheet.rules.is_empty() || sheet.rules[0].declarations.is_empty() {
                return String::new();
            }
            css::mapper::map_declarations(&sheet.rules[0].declarations, &sheet.variables)
        }
        Err(_) => String::new(),
    }
}

fn apply_bind_attr(name: &str, expr: &str, loop_vars: &[&str], computed: &[&str]) -> String {
    match name {
        "value" => format!(".child(format!(\"{{}}\", {}))", gen_expr_code(expr, loop_vars, computed)),
        "class" | "id" | "style" => String::new(),
        "disabled" | "checked" | "readonly" => format!(".when({}, |el| el)", gen_expr_code(expr, loop_vars, computed)),
        _ => format!(".child(format!(\"{{}}\", {}))", gen_expr_code(expr, loop_vars, computed)),
    }
}

fn gen_mixed_text(segments: &[TextSegment], loop_vars: &[&str], computed: &[&str]) -> String {
    let mut fmt_str = String::new();
    let mut args = Vec::new();
    for seg in segments {
        match seg {
            TextSegment::Literal(s) => {
                fmt_str.push_str(&s.replace('{', "{{").replace('}', "}}"));
            }
            TextSegment::Interpolation(expr) => {
                fmt_str.push_str("{}");
                args.push(gen_expr_code(expr, loop_vars, computed));
            }
        }
    }
    if args.is_empty() {
        format!("{:?}", fmt_str)
    } else {
        format!("format!({:?}, {})", fmt_str, args.join(", "))
    }
}

/// 把插值表达式字符串编译为 Rust 表达式字符串
fn gen_expr_code(expr_str: &str, loop_vars: &[&str], computed: &[&str]) -> String {
    if let Some(code) = try_gen_i18n_call(expr_str, loop_vars, computed) {
        return code;
    }
    match expr::parse(expr_str) {
        Ok(expr::Expr::Field(name)) if computed.iter().any(|c| *c == name.as_str()) => {
            if loop_vars.iter().any(|v| *v == name) {
                format!("{}()", name)
            } else {
                format!("self.{}()", name)
            }
        }
        Ok(parsed) => expr::to_rust_code_with_ctx(&parsed, loop_vars),
        Err(_) => {
            let trimmed = expr_str.trim();
            if loop_vars.iter().any(|v| *v == trimmed) {
                trimmed.to_string()
            } else if computed.iter().any(|c| *c == trimmed) {
                format!("self.{}()", trimmed)
            } else {
                format!("self.{}", trimmed)
            }
        }
    }
}

/// `{t("key")}` → `cx.t("key")`
pub(crate) fn try_gen_i18n_call(expr_str: &str, loop_vars: &[&str], computed: &[&str]) -> Option<String> {
    let trimmed = expr_str.trim();
    if !trimmed.starts_with("t(") || !trimmed.ends_with(')') {
        return None;
    }
    let inner = trimmed[2..trimmed.len() - 1].trim();
    if inner.is_empty() {
        return None;
    }
    if (inner.starts_with('"') && inner.ends_with('"') && inner.len() >= 2)
        || (inner.starts_with('\'') && inner.ends_with('\'') && inner.len() >= 2)
    {
        let key = &inner[1..inner.len() - 1];
        return Some(format!("cx.t({key:?})"));
    }
    let key_expr = gen_expr_code(inner, loop_vars, computed);
    Some(format!("cx.t(&{key_expr})"))
}
