//! 代码生成器（核心入口）
//!
//! 将 AST 转换为 Rust 源码字符串（`impl Render for <View>`）。
//! 详见文档 §10.6 代码生成。
//!
//! 生成代码通过 `include!` 注入用户模块，因此：
//! - 全部使用完全限定路径（`gpui::*`、`rml::runtime::*`），避免与用户 import 冲突
//! - 事件回调统一通过 `rml::runtime::event_flow::convert::from_gpui_*` 转换 GPUI 事件 → RML 事件
//! - GPUI 事件监听器（on_click 等）要求元素为 `Stateful<Div>`，需先调用 `.id(...)` 赋予 ID
//!
//! ## 模块职责
//!
//! - `mod.rs`（本文件）：入口 `codegen()` 函数，按根标签分派到 window/observable/render
//! - `node.rs`：节点代码生成（gen_node + gen_element）
//! - `attribute.rs`：属性代码生成（静态/CSS/内联/绑定）
//! - `text.rs`：文本与表达式代码生成（混合文本/插值/i18n）
//! - `model.rs`：Model 字段收集
//! - `render.rs`：`impl Render` 生成
//! - `window.rs`：窗口/对话框 impl 生成（`impl IWindow` / `open`+`close`）
//! - `shell.rs`：窗口外壳包裹（ModernWindowShell / TabWindowShell）
//! - `binding.rs`：双向绑定与字段校验代码生成
//! - `observable.rs`：Observable 版本管理 + 计算属性缓存 + InputState 同步
//! - `event.rs`：事件绑定代码生成（onclick → .on_click 等）
//! - `component.rs`：gpui-component 扩展组件生成（Button/Input 等）
//! - `expr.rs`：表达式解析器（{count + 1} → AST → Rust 代码）

pub(crate) mod attribute;
pub(crate) mod binding;
mod lifecycle;
mod model;
pub(crate) mod node;
mod observable;
mod once;
pub(crate) mod render;
mod shell;
pub(crate) mod style_attr;
pub(crate) mod text;
pub(crate) mod window;

use crate::compiler::{CodegenCtx, CodegenError};

pub use model::{collect_model_converters, collect_model_fields, collect_model_input_handlers};
pub use node::{gen_node, GenResult};
pub(crate) use text::{gen_expr_code, try_gen_i18n_call};

/// 生成 `impl Render for <ViewStruct>` 代码块（可能附带 `impl IWindow`）
///
/// RML 根节点必须是 `<window>`、`<modern-window>`、`<tab-window>`、`<dialog>` 或 `<component>`：
/// - `<window>`/`<modern-window>`/`<tab-window>`：生成 `impl IWindow` + `impl Render`
/// - `<dialog>`：生成 `open(window, cx)` / `close(cx)` 方法 + `impl Render`
/// - `<component>`：仅生成 `impl Render`
pub fn codegen(root: &crate::parser::ast::Node, ctx: &CodegenCtx) -> Result<String, CodegenError> {
    use crate::parser::ast::Node;

    let elem = match root {
        Node::Element(e) => e,
        _ => {
            return Err(CodegenError {
                message: format!(
                    "root element must be <window>, <modern-window>, <tab-window>, <dialog>, or <component>; got <{}>",
                    root
                ),
                span: None,
            });
        }
    };

    let translator = ctx.registry.resolve(elem).ok_or_else(|| CodegenError {
        message: format!("unknown root tag: <{}>", elem.tag),
        span: Some(elem.span),
    })?;

    if !translator.metadata().is_root {
        return Err(CodegenError {
            message: format!(
                "root element must be <window>, <modern-window>, <tab-window>, <dialog>, or <component>; got <{}>",
                elem.tag
            ),
            span: Some(elem.span),
        });
    }

    let mut out = String::new();
    out.push_str("// Auto-generated by RML compiler. DO NOT EDIT.\n");
    out.push_str("#[allow(unused_imports, unused_variables, non_snake_case, dead_code)]\n\n");

    // 根节点 translator 生成窗口/对话框 impl + impl Render
    let (code, _) = translator.to_rust(elem, ctx, &mut 0, &[], &[])?;
    out.push_str(&code);

    // 版本管理方法 + 计算属性包装方法
    out.push_str(&observable::gen_observable_impl(ctx));
    out.push('\n');
    out.push_str(&observable::gen_computed_wrappers(ctx));
    out.push('\n');

    // InputState 惰性初始化方法
    out.push_str(&observable::gen_input_state_impl(ctx));

    // 生命周期钩子自动联动（#[on_loaded]/#[on_unloaded] → impl ILifecycle）
    out.push_str(&lifecycle::gen_lifecycle_impl(ctx));

    // 后处理 sourcemap：扫描 /*__rml_sm:S:E*/ 标记，记录到 ctx.source_map 并从 out 删除
    postprocess_sourcemap(&mut out, &mut ctx.source_map.borrow_mut());

    Ok(out)
}

/// 后处理 sourcemap 标记
///
/// codegen 在 gen_node_impl 入口为每个 Element/Interpolation 节点的 code 前注入了
/// 行内注释标记 `/*__rml_sm:S:E*/`（S/E 为 AST span 字节偏移）。
/// 本函数扫描 out 中所有标记，对每个标记：
/// 1. 记录 (span=S..E, rust_line=标记所在行 1-based, rust_col=标记在该行的列号 1-based)
///    到 source_map
/// 2. 从 out 中删除标记（保持行号不变，因为标记是行内的）
///
/// 删除后 out 为干净的 Rust 代码，sourcemap 携带每个 AST 节点 span 到生成代码位置的映射。
fn postprocess_sourcemap(out: &mut String, source_map: &mut crate::compiler::source_map::SourceMap) {
    use regex::Regex;
    let re = Regex::new(r"/\*__rml_sm:(\d+):(\d+)\*/").unwrap();

    // 收集所有标记的 (span, line, col) 与匹配位置
    let mut entries: Vec<((usize, usize), u32, u32)> = Vec::new();
    let mut matches_to_remove: Vec<(usize, usize)> = Vec::new();

    for m in re.find_iter(out) {
        let caps = re.captures(m.as_str()).unwrap();
        let start: usize = caps[1].parse().unwrap_or(0);
        let end: usize = caps[2].parse().unwrap_or(0);

        // 计算 m.start() 字节偏移对应的行号与列号（1-based）
        let prefix = &out[..m.start()];
        let line = prefix.matches('\n').count() as u32 + 1;
        // 列号：m.start() 在该行中的字节位置（1-based）
        let last_newline = prefix.rfind('\n').map(|i| i + 1).unwrap_or(0);
        let col = (m.start() - last_newline) as u32 + 1;

        entries.push(((start, end), line, col));
        matches_to_remove.push((m.start(), m.end()));
    }

    // 记录到 source_map
    for ((start, end), line, col) in entries {
        source_map.record(crate::parser::Span::new(start, end), line, col);
    }

    // 从后往前删除标记，避免偏移前面的索引
    for (start, end) in matches_to_remove.into_iter().rev() {
        out.replace_range(start..end, "");
    }
}

/// 从 code 字符串中删除所有 sourcemap 标记，不做 sourcemap 记录
///
/// 供单元测试使用：测试直接调用各组件生成函数（绕过 codegen 主入口的
/// postprocess_sourcemap），用此函数清理 code 后再做断言。
#[allow(dead_code)]
pub(crate) fn strip_sourcemap_markers(code: &str) -> String {
    use regex::Regex;
    let re = Regex::new(r"/\*__rml_sm:\d+:\d+\*/").unwrap();
    re.replace_all(code, "").to_string()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::compiler::CodegenCtx;
    use crate::parser::ast::Node;

    /// 构造最小可用的 CodegenCtx：设置 view_struct_name 与内置 translator 注册表。
    fn minimal_ctx() -> CodegenCtx {
        CodegenCtx {
            view_struct_name: "TestView".to_string(),
            registry: crate::compiler::translator::TranslatorRegistry::builtin(),
            ..Default::default()
        }
    }

    // ─── 错误路径：非 Element 根节点 ───

    #[test]
    fn codegen_text_root_returns_error() {
        let root = Node::Text("hello".to_string());
        let result = codegen(&root, &minimal_ctx());
        assert!(result.is_err());
        let err = result.unwrap_err();
        assert!(
            err.message.contains("root element must be"),
            "expected root element error, got: {}",
            err.message
        );
    }

    #[test]
    fn codegen_interpolation_root_returns_error() {
        let root = Node::Interpolation { expr: "count".to_string(), span: crate::parser::Span::empty() };
        let result = codegen(&root, &minimal_ctx());
        assert!(result.is_err());
    }

    #[test]
    fn codegen_mixed_text_root_returns_error() {
        let root = Node::MixedText(vec![]);
        let result = codegen(&root, &minimal_ctx());
        assert!(result.is_err());
    }

    // ─── 错误路径：Element 但非根标签 ───

    #[test]
    fn codegen_non_root_tag_returns_error() {
        // <div> 不是根标签（window/modern-window/tab-window/dialog/component）
        let root = crate::parser::parse("<div></div>").unwrap();
        let result = codegen(&root, &minimal_ctx());
        assert!(result.is_err());
        let err = result.unwrap_err();
        assert!(
            err.message.contains("root element must be"),
            "expected root element error, got: {}",
            err.message
        );
    }

    #[test]
    fn codegen_button_root_returns_error() {
        let root = crate::parser::parse("<button></button>").unwrap();
        assert!(codegen(&root, &minimal_ctx()).is_err());
    }

    // ─── 成功路径：各根标签可生成代码 ───

    #[test]
    fn codegen_component_root_succeeds() {
        let root = crate::parser::parse("<component></component>").unwrap();
        let result = codegen(&root, &minimal_ctx());
        assert!(result.is_ok(), "codegen failed: {:?}", result.err());
        let code = result.unwrap();
        // 确认生成代码包含自动生成注释和 impl Render
        assert!(
            code.contains("// Auto-generated by RML compiler. DO NOT EDIT."),
            "expected auto-generated header"
        );
        assert!(
            code.contains("impl gpui::Render for TestView"),
            "expected impl Render for TestView, got snippet: {}",
            code.chars().take(300).collect::<String>()
        );
    }

    #[test]
    fn codegen_window_root_succeeds() {
        let root = crate::parser::parse("<window></window>").unwrap();
        let result = codegen(&root, &minimal_ctx());
        assert!(result.is_ok(), "codegen failed: {:?}", result.err());
        let code = result.unwrap();
        assert!(code.contains("impl gpui::Render for TestView"));
    }

    #[test]
    fn codegen_dialog_root_succeeds() {
        let root = crate::parser::parse("<dialog></dialog>").unwrap();
        let result = codegen(&root, &minimal_ctx());
        assert!(result.is_ok(), "codegen failed: {:?}", result.err());
        let code = result.unwrap();
        assert!(code.contains("impl gpui::Render for TestView"));
    }

    #[test]
    fn codegen_modern_window_root_succeeds() {
        let root = crate::parser::parse("<modern-window></modern-window>").unwrap();
        let result = codegen(&root, &minimal_ctx());
        assert!(result.is_ok(), "codegen failed: {:?}", result.err());
        let code = result.unwrap();
        assert!(code.contains("impl gpui::Render for TestView"));
    }

    #[test]
    fn codegen_tab_window_root_succeeds() {
        let root = crate::parser::parse("<tab-window></tab-window>").unwrap();
        let result = codegen(&root, &minimal_ctx());
        assert!(result.is_ok(), "codegen failed: {:?}", result.err());
        let code = result.unwrap();
        assert!(code.contains("impl gpui::Render for TestView"));
    }

    // ─── 烟雾测试：生成代码结构完整性 ───

    #[test]
    fn codegen_component_with_child_generates_render_body() {
        // <component><div></div></component> → render 方法体非空
        let root = crate::parser::parse("<component><div></div></component>").unwrap();
        let code = codegen(&root, &minimal_ctx()).unwrap();
        // render 方法签名应出现
        assert!(
            code.contains("fn render(&mut self, _window: &mut gpui::Window, cx: &mut gpui::Context<Self>)"),
            "expected render method signature"
        );
    }

    #[test]
    fn codegen_includes_rml_render_guard() {
        // 所有 codegen 输出应包含 RenderThreadGuard::enter() 调用
        let root = crate::parser::parse("<component></component>").unwrap();
        let code = codegen(&root, &minimal_ctx()).unwrap();
        assert!(
            code.contains("RenderThreadGuard::enter()"),
            "expected RenderThreadGuard::enter() in generated code"
        );
    }

    #[test]
    fn codegen_includes_lifecycle_hook_call() {
        // 所有 codegen 输出应在 render 入口处调用 on_loaded（仅首次）
        let root = crate::parser::parse("<component></component>").unwrap();
        let code = codegen(&root, &minimal_ctx()).unwrap();
        assert!(
            code.contains("ILifecycle::on_loaded"),
            "expected ILifecycle::on_loaded call in render"
        );
    }

    #[test]
    fn codegen_empty_component_uses_div_placeholder() {
        // 空子节点应使用 gpui::div() 占位
        let root = crate::parser::parse("<component></component>").unwrap();
        let code = codegen(&root, &minimal_ctx()).unwrap();
        assert!(
            code.contains("gpui::div()"),
            "expected gpui::div() placeholder for empty body"
        );
    }
}
