//! 代码生成器
//!
//! 将 AST 转换为 Rust 源码字符串（`impl Render for <View>`）。
//! 详见文档 §10.6 代码生成。
//!
//! 生成代码通过 `include!` 注入用户模块，因此：
//! - 全部使用完全限定路径（`gpui::*`、`rml::runtime::*`），避免与用户 import 冲突
//! - 事件回调统一通过 `rml::runtime::event_flow::convert::from_gpui_*` 转换 GPUI 事件 → RML 事件
//! - GPUI 事件监听器（on_click 等）要求元素为 `Stateful<Div>`，需先调用 `.id(...)` 赋予 ID

use crate::compiler::CodegenCtx;
use crate::parser::ast::{Attribute, Directive, Element, EventHandler, Node, TextSegment};
use crate::tags;
use std::fmt;

#[derive(Debug, Clone)]
pub struct CodegenError {
    pub message: String,
}

impl fmt::Display for CodegenError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "Codegen error: {}", self.message)
    }
}

impl std::error::Error for CodegenError {}

/// 生成 `impl Render for <ViewStruct>` 代码块
pub fn codegen(root: &Node, ctx: &CodegenCtx) -> Result<String, CodegenError> {
    let mut out = String::new();
    let view_name = &ctx.view_struct_name;

    out.push_str("// Auto-generated by RML compiler. DO NOT EDIT.\n");
    out.push_str("#[allow(unused_imports, unused_variables, non_snake_case, dead_code)]\n");

    out.push_str(&format!("impl gpui::Render for {} {{\n", view_name));
    out.push_str(
        "    fn render(&mut self, _window: &mut gpui::Window, cx: &mut gpui::Context<Self>) -> impl gpui::IntoElement {\n",
    );
    // 函数内 use：GPUI trait 方法（.child/.on_click/.id 等）必须在作用域内
    out.push_str("        use gpui::{ParentElement, InteractiveElement, StatefulInteractiveElement, IntoElement};\n");
    out.push_str("        use rml::runtime::event_flow::convert as rml_convert;\n");

    let mut id_counter: usize = 0;
    let root_expr = gen_node(root, ctx, 0, &mut id_counter)?;
    out.push_str(&format!("        {}\n", root_expr));
    out.push_str("    }\n");
    out.push_str("}\n");

    Ok(out)
}

/// 为单个节点生成构建代码，返回一个表达式字符串
fn gen_node(
    node: &Node,
    ctx: &CodegenCtx,
    depth: usize,
    id_counter: &mut usize,
) -> Result<String, CodegenError> {
    match node {
        Node::Element(elem) => gen_element(elem, ctx, depth, id_counter),
        Node::Text(text) => Ok(format!("{:?}", text)),
        Node::Interpolation(expr) => {
            // 单个插值：{field} → format!("{}", self.field)
            // String 实现 IntoElement，可作为 child 直接传入
            Ok(format!("format!(\"{{}}\", self.{})", expr))
        }
        Node::MixedText(segments) => Ok(gen_mixed_text(segments)),
    }
}

fn gen_element(
    elem: &Element,
    ctx: &CodegenCtx,
    depth: usize,
    id_counter: &mut usize,
) -> Result<String, CodegenError> {
    let tag = &elem.tag;

    // 自定义组件在 Phase B-1 不支持
    if tags::is_component(tag) {
        return Err(CodegenError {
            message: format!("custom component <{}> not supported in Phase B-1", tag),
        });
    }

    let builtin = tags::lookup(tag).ok_or_else(|| CodegenError {
        message: format!("unknown tag: <{}>", tag),
    })?;

    // 1. 生成元素构造调用
    let mut code = String::from(builtin.codegen_ctor());

    // 2. 检查是否有事件处理器 —— 若有，必须先 .id() 使元素成为 Stateful<Div>
    //    GPUI 的 on_click/on_key_down 等方法定义在 StatefulInteractiveElement trait 上，
    //    仅 Stateful<T> 实现该 trait。Div 实现 InteractiveElement::id() 返回 Stateful<Div>。
    let has_events = elem
        .attributes
        .iter()
        .any(|attr| matches!(attr, Attribute::Event { .. }));

    if has_events {
        let id_val = *id_counter;
        *id_counter += 1;
        // 使用 ("rml_el", n) 元组作为 ElementId，GPUI 支持 From<(&'static str, usize)>
        // 显式标注 usize 避免整数字面量默认推断为 i32
        code.push_str(&format!(".id((\"rml_el\", {}usize))", id_val));
    }

    // 3. 应用静态属性与绑定属性
    for attr in &elem.attributes {
        match attr {
            Attribute::Static { name, value } => {
                code.push_str(&apply_static_attr(name, value));
            }
            Attribute::Bind { name, expr } => {
                code.push_str(&apply_bind_attr(name, expr));
            }
            Attribute::Event { name, handler } => {
                code.push_str(&apply_event(name, handler, ctx));
            }
        }
    }

    // 4. 处理 model 指令：input/textarea 的双向绑定
    //    Phase B-1 简化：仅生成 value 显示，Phase B-2 补全 on_change 回写
    for d in &elem.directives {
        if let Directive::Model(field) = d {
            code.push_str(&format!(".child(format!(\"{{}}\", self.{}))", field));
        }
    }

    // 5. 处理子节点
    for child in &elem.children {
        let child_code = gen_node(child, ctx, depth + 1, id_counter)?;
        code.push_str(&format!("\n            .child({})", child_code));
    }

    // 6. 处理 if/show 指令：条件渲染
    //    .when() 不会隐藏元素，必须用 if/else 表达式包裹，返回 AnyElement 统一类型
    let cond: Option<String> = elem.directives.iter().find_map(|d| match d {
        Directive::If(c) => Some(c.clone()),
        Directive::Show(c) => Some(c.clone()),
        _ => None,
    });

    if let Some(cond) = cond {
        // 生成条件表达式：if self.<cond> { <element> } else { gpui::Empty }
        // 两分支均调用 .into_any_element() 统一为 AnyElement
        Ok(format!(
            "if self.{} {{ {}.into_any_element() }} else {{ gpui::Empty.into_any_element() }}",
            cond, code
        ))
    } else {
        Ok(code)
    }
}

fn apply_static_attr(name: &str, value: &str) -> String {
    match name {
        // class/id 在 Phase B-1 跳过（Phase B-3 样式系统实现）
        "class" | "id" | "style" => String::new(),
        // src/href 等 URL 属性跳过（Phase B-2 资源系统实现）
        "src" | "href" => String::new(),
        // type 属性（button/checkbox 等）跳过（Phase B-2 表单系统实现）
        "type" => String::new(),
        // 其他静态属性作为子文本节点（调试用）
        _ => format!(".child({:?})", format!("{}={}", name, value)),
    }
}

fn apply_bind_attr(name: &str, expr: &str) -> String {
    match name {
        // value 绑定：将字段值格式化为文本子节点
        "value" => format!(".child(format!(\"{{}}\", self.{}))", expr),
        // class/id/style 绑定在 Phase B-1 跳过
        "class" | "id" | "style" => String::new(),
        // disabled/checked：用 .when() 控制元素状态（仅当 true 时生效）
        // 注：.when(false) 返回原元素不变，无法真正禁用 —— Phase B-2 修复
        "disabled" | "checked" | "readonly" => format!(".when(self.{}, |el| el)", expr),
        // 其他绑定属性作为文本子节点（调试用）
        _ => format!(".child(format!(\"{{}}\", self.{}))", expr),
    }
}

/// 事件名 → (GPUI 事件类型, GPUI on_* 方法名, 转换函数路径)
///
/// 返回 (event_type, on_method, convert_expr):
/// - `event_type`：GPUI 事件类型名，用于闭包参数标注
/// - `on_method`：GPUI StatefulInteractiveElement 方法名
/// - `convert_expr`：调用 rml_convert 的表达式，传入 GPUI 事件引用，返回 RML 事件对象
fn event_binding(name: &str) -> Option<(&'static str, &'static str, &'static str)> {
    match name {
        // 鼠标事件
        "onclick" => Some(("gpui::ClickEvent", "on_click", "rml_convert::from_gpui_click(ev)")),
        "onmousedown" => Some((
            "gpui::MouseDownEvent",
            "on_mouse_down",
            "rml_convert::from_gpui_mouse_down(ev)",
        )),
        "onmouseup" => Some((
            "gpui::MouseUpEvent",
            "on_mouse_up",
            "rml_convert::from_gpui_mouse_up(ev)",
        )),
        "onmousemove" => Some((
            "gpui::MouseMoveEvent",
            "on_mouse_move",
            "rml_convert::from_gpui_mouse_move(ev)",
        )),
        "onwheel" => Some((
            "gpui::ScrollWheelEvent",
            "on_scroll_wheel",
            "rml_convert::from_gpui_scroll_wheel(ev)",
        )),
        // 键盘事件
        "onkeydown" => Some((
            "gpui::KeyDownEvent",
            "on_key_down",
            "rml_convert::from_gpui_key_down(ev)",
        )),
        "onkeyup" => Some((
            "gpui::KeyUpEvent",
            "on_key_up",
            "rml_convert::from_gpui_key_up(ev)",
        )),
        // 焦点事件（onblur 有 FocusOutEvent，onfocus 无对应 GPUI 类型）
        "onblur" => Some((
            "gpui::FocusOutEvent",
            "on_focus_out",
            "rml_convert::from_gpui_focus_out(ev)",
        )),
        // 以下事件 GPUI 不直接提供对应类型，Phase B-2 由 codegen 直接构造 RML 事件
        // 暂不绑定（返回 None）
        "oninput" | "onchange" | "onsubmit" | "onfocus" | "onload" | "onresize" | "onscroll" => None,
        _ => None,
    }
}

fn apply_event(name: &str, handler: &EventHandler, _ctx: &CodegenCtx) -> String {
    // 未知事件名：跳过
    let (gpui_type, on_method, convert_expr) = match event_binding(name) {
        Some(binding) => binding,
        None => return String::new(),
    };

    match handler {
        EventHandler::Ident(method) | EventHandler::MethodName(method) => {
            // .on_click(cx.listener(move |this, ev: &gpui::ClickEvent, _window, cx| {
            //     let rml_ev = rml_convert::from_gpui_click(ev);
            //     this.increment(&rml_ev, cx);
            // }))
            format!(
                ".{}(cx.listener(move |this, ev: &{}, _window, cx| {{\n                    \
                 let rml_ev = {};\n                    this.{}(&rml_ev, cx);\n                }}))",
                on_method, gpui_type, convert_expr, method
            )
        }
        EventHandler::WithArgs(method, args) => {
            if args.is_empty() {
                format!(
                    ".{}(cx.listener(move |this, ev: &{}, _window, cx| {{\n                    \
                     let rml_ev = {};\n                    this.{}(&rml_ev, cx);\n                }}))",
                    on_method, gpui_type, convert_expr, method
                )
            } else {
                // Phase B-1 简化：仅支持单参数
                let arg = &args[0];
                format!(
                    ".{}(cx.listener(move |this, ev: &{}, _window, cx| {{\n                    \
                     let p0 = {}.clone();\n                    let rml_ev = {};\n                    \
                     this.{}(p0, &rml_ev, cx);\n                }}))",
                    on_method, gpui_type, arg, convert_expr, method
                )
            }
        }
    }
}

fn gen_mixed_text(segments: &[TextSegment]) -> String {
    // 构建 format! 调用
    let mut fmt_str = String::new();
    let mut args = Vec::new();
    for seg in segments {
        match seg {
            TextSegment::Literal(s) => {
                fmt_str.push_str(&s.replace('{', "{{").replace('}', "}}"));
            }
            TextSegment::Interpolation(expr) => {
                fmt_str.push_str("{}");
                args.push(format!("self.{}", expr));
            }
        }
    }
    if args.is_empty() {
        format!("{:?}", fmt_str)
    } else {
        format!("format!({:?}, {})", fmt_str, args.join(", "))
    }
}
