//! RML 案例库模块

#[path = "welcome_case.rml.rs"]
pub mod welcome_case;
#[path = "counter_case.rml.rs"]
pub mod counter_case;
#[path = "two_way_case.rml.rs"]
pub mod two_way_case;
#[path = "button_case.rml.rs"]
pub mod button_case;
#[path = "accordion_case.rml.rs"]
pub mod accordion_case;
#[path = "tab_bar_case.rml.rs"]
pub mod tab_bar_case;
#[path = "avatar_case.rml.rs"]
pub mod avatar_case;
#[path = "i18n_case.rml.rs"]
pub mod i18n_case;
#[path = "menu_context_case.rml.rs"]
pub mod menu_context_case;
#[path = "menu_dropdown_case.rml.rs"]
pub mod menu_dropdown_case;
#[path = "menu_editor_case.rml.rs"]
pub mod menu_editor_case;
#[path = "menu_features_case.rml.rs"]
pub mod menu_features_case;
#[path = "menu_custom_case.rml.rs"]
pub mod menu_custom_case;
#[path = "status_bar_case.rml.rs"]
pub mod status_bar_case;
#[path = "slot_case.rml.rs"]
pub mod slot_case;
#[path = "table_case.rml.rs"]
pub mod table_case;
#[path = "description_list_case.rml.rs"]
pub mod description_list_case;

// M1 任务 1.3：17 个组件独立 demo
#[path = "badge_case.rml.rs"]
pub mod badge_case;
#[path = "label_case.rml.rs"]
pub mod label_case;
#[path = "separator_case.rml.rs"]
pub mod separator_case;
#[path = "tag_case.rml.rs"]
pub mod tag_case;
#[path = "progress_case.rml.rs"]
pub mod progress_case;
#[path = "progress_circle_case.rml.rs"]
pub mod progress_circle_case;
#[path = "button_group_case.rml.rs"]
pub mod button_group_case;
#[path = "avatar_group_case.rml.rs"]
pub mod avatar_group_case;
#[path = "card_case.rml.rs"]
pub mod card_case;
#[path = "title_bar_case.rml.rs"]
pub mod title_bar_case;
#[path = "native_status_bar_case.rml.rs"]
pub mod native_status_bar_case;
#[path = "checkbox_case.rml.rs"]
pub mod checkbox_case;
#[path = "switch_case.rml.rs"]
pub mod switch_case;
#[path = "input_case.rml.rs"]
pub mod input_case;
#[path = "tree_case.rml.rs"]
pub mod tree_case;
#[path = "slider_case.rml.rs"]
pub mod slider_case;
#[path = "code_editor_case.rml.rs"]
pub mod code_editor_case;
